"use client";
import { useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import MagneticButton from "@/components/ui/MagneticButton";
gsap.registerPlugin(ScrollTrigger);
export default function Hero() {
    const section = useRef<HTMLElement>(null), video = useRef<HTMLVideoElement>(null);
    useLayoutEffect(() => { const ctx = gsap.context(() => { gsap.timeline({ delay: .25 }).from(".hero-kicker,.hero-title,.hero-copy,.hero-actions", { y: 35, opacity: 0, stagger: .08, duration: 1, ease: "power3.out" }); if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; gsap.to(video.current, { scale: 1.06, ease: "none", scrollTrigger: { trigger: section.current, start: "top top", end: "bottom top", scrub: true } }) }, section); return () => ctx.revert() }, []);
    return <section ref={section} className="relative flex min-h-screen items-end overflow-hidden bg-[#090909] text-white grain"><video ref={video} className="hero-video absolute inset-0 h-full w-full object-cover" poster="/video/hero_poster1.jpeg" autoPlay loop muted playsInline preload="auto"><source src="/video/hero.mp4" type="video/mp4" /></video><div className="hero-noise absolute inset-0" /><div className="relative z-10 w-full pb-14 pt-32 md:pb-24 md:pt-40"><div className="container"><p className="hero-kicker eyebrow mb-5">Built for Island Life · St. Vincent & the Grenadines</p><h1 className="hero-title font-display max-w-5xl text-balance text-5xl leading-[.9] sm:text-6xl md:text-[clamp(5rem,10vw,9.5rem)]">Modern homes.<br /><span className="text-[#d2c5b3]">Island living.</span></h1><p className="hero-copy mt-7 max-w-2xl text-base leading-relaxed text-white/80 sm:text-lg md:text-xl">Affordable, modern and sustainable living solutions — thoughtfully designed for your lifestyle and budget.</p><div className="hero-actions mt-8 flex max-w-xl flex-wrap gap-3"><MagneticButton href="#models" className="hero-link w-full sm:w-auto">Explore homes <span className="ml-2">↓</span></MagneticButton><MagneticButton href="#contact" className="hero-link w-full sm:w-auto">Get your free quote ↗</MagneticButton></div><div className="mt-12 flex flex-wrap items-center gap-5 text-xs font-bold uppercase tracking-[.18em] text-white/55"><span>Affordable</span><span>Premium quality</span><span>Fast delivery</span><span>Customizable</span></div></div></div></section>
}
